[package]
name = "rua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
pretty_assertions = "1.4.0"

[dependencies]
rustc-hash = "1.1.0"
thiserror = "1.0.49"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.dev]
opt-level = 3

[profile.bench]
debug = true

[[bench]]
name = "lex_bench"
harness = false

[[bench]]
name = "parser_bench"
harness = false

