name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: clippy
      run: cargo clippy --all-targets -- -Dwarnings
    - name: fmt
      run: cargo fmt --check
    - name: Build
      run: cargo test --no-run
    - name: Run tests
      run: cargo test
